name: Pull Request
on:
    push:
        branches:
            - master
jobs:
    createPullRequest:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Test
              id: test
              uses: ./
              with:
                  whoToGreet: 'Bella'
