name: Pull Request
on:
    push:
        branches:
            - master
jobs:
    createPullRequest:
        runs-on: ubuntu-latest
        steps:
            - uses: action/checkout@v2
            - name: Create Pull Request
              id: cpr
              uses: peter-evans/create-pull-request@v2
