name: Pull Request
on:
    push:
        branches:
            - master
jobs:
    pr:
        runs-on: ubuntu-latest
        steps:
            - uses: action/checkout@v2
            - name: Create Pull Request
              id: cpr
              uses: peter-evans/create-pull-request@v2
              with:
                  token: ${{ secrets.TOKEN }}
                  committer: Gabriel Joshua Paet <gjvpaet@gmail.com>
                  author: ${{ github.actor }}
                  title: Sample
