name: Pull Request
on:
    push:
        branches:
            - master
jobs:
    createPullRequest:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@v2
              with:
                  path: input-file
            - name: Install Dependencies
              id: install-deps
              run: cd input-file/ && yarn install
            - name: Test
              id: test
              uses: ./
              with:
                  githubToken: d43a4364909c54dab1bdf8dd9b7aec7add8b13a2
